# Generated by Django 4.2.11 on 2024-03-06 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_goal_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='priority',
            new_name='completed',
        ),
    ]
